# Generated by Django 4.1.3 on 2022-12-23 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Levels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(db_index=True, max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Words',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=70)),
                ('translate', models.CharField(max_length=70)),
                ('user_level', models.CharField(max_length=10, null=True)),
                ('word_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.levels')),
            ],
        ),
    ]
